project_id = "oevxapmcmcaxpaluehyg"
[functions.create-invitation]
enabled = true
verify_jwt = true
import_map = "./functions/create-invitation/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-invitation/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-invitation/*.html" ]

[functions.test-function]
enabled = true
verify_jwt = true
import_map = "./functions/test-function/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/test-function/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/test-function/*.html" ]

[functions.ai-verification]
enabled = true
verify_jwt = true
import_map = "./functions/ai-verification/deno.json"
entrypoint = "./functions/ai-verification/index.ts"
